"""Added the new colomun for base price

Revision ID: 0bb448e97780
Revises: be1d3daa1da6
Create Date: 2026-03-24 17:36:02.609807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb448e97780'
down_revision: Union[str, Sequence[str], None] = 'be1d3daa1da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_tiers', sa.Column('base_price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_tiers', 'base_price')
    # ### end Alembic commands ###
