"""Added Twilio phone and Stripe integration columns

Revision ID: c0982d514b7c
Revises: 0bb448e97780
Create Date: 2026-03-27 18:34:51.306357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0982d514b7c'
down_revision: Union[str, Sequence[str], None] = '0bb448e97780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['transaction_id'])
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_connect_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_reset_password_token_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['stripe_connect_id'])
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'reset_password_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_reset_password_token_key'), 'users', ['reset_password_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'stripe_connect_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
